name : pipeline 
on : 
    push : 
        branches : [main]
    pull_request : 
        branches : [main]

jobs :
    test :
        runs-on :ubuntu-latest
        
        steps:
            - name :check out code
              uses : actions/checkout@v4
            - name : set up python
              uses : actions/setup-python@v5
              with :
                python-version : '3.12'

            - name : install dependencies
              run : pip install -r requirements.txt

            - name : run python check
              run : python manage.py check
            - name : run test
              run  : python manage.py test
            